"""Project-level collection of reusable annotator profiles."""

from __future__ import annotations

import json
from pathlib import Path
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from heva.workflow.document_metadata import AnnotatorMetadata


ANNOTATORS_PATH = Path("data/annotators.json")
LEGACY_ANNOTATOR_PATH = Path("data/annotator.json")


class AnnotatorRecord(AnnotatorMetadata):
    """One reusable annotator identity within a HEVA project."""

    annotator_id: str = Field(
        default_factory=lambda: f"ANN-{uuid4().hex[:12].upper()}",
        description="Stable project identifier generated by HEVA.",
    )


class AnnotatorRegistry(BaseModel):
    """Persistent collection and currently selected annotator."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = "1.0"
    active_annotator_id: str | None = None
    annotators: list[AnnotatorRecord] = Field(default_factory=list)

    def active(self) -> AnnotatorRecord | None:
        return next(
            (
                annotator
                for annotator in self.annotators
                if annotator.annotator_id == self.active_annotator_id
            ),
            None,
        )


class AnnotatorRegistryError(ValueError):
    """Raised when the annotator registry cannot be read or updated."""


def _clean_profile(profile: AnnotatorMetadata) -> AnnotatorMetadata:
    return profile.model_copy(
        update={
            field: value.strip() if isinstance(value, str) and value.strip() else None
            for field, value in profile.model_dump().items()
        }
    )


def load_annotator_registry(project_root: str | Path) -> AnnotatorRegistry:
    """Load the collection, falling back to the former single-profile file."""

    root = Path(project_root)
    path = root / ANNOTATORS_PATH
    try:
        return AnnotatorRegistry.model_validate_json(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        legacy_path = root / LEGACY_ANNOTATOR_PATH
        try:
            legacy = AnnotatorMetadata.model_validate_json(
                legacy_path.read_text(encoding="utf-8")
            )
        except FileNotFoundError:
            return AnnotatorRegistry()
        except (OSError, ValidationError) as error:
            raise AnnotatorRegistryError(
                "The saved annotator profile cannot be read."
            ) from error
        record = AnnotatorRecord(**legacy.model_dump())
        registry = AnnotatorRegistry(
            active_annotator_id=record.annotator_id,
            annotators=[record],
        )
        save_annotator_registry(root, registry)
        return registry
    except (OSError, ValidationError) as error:
        raise AnnotatorRegistryError(
            "The annotator collection cannot be read."
        ) from error


def save_annotator_registry(
    project_root: str | Path,
    registry: AnnotatorRegistry,
) -> Path:
    """Atomically persist the reusable annotator collection."""

    path = Path(project_root) / ANNOTATORS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".json.tmp")
    temporary.write_text(
        json.dumps(registry.model_dump(mode="json"), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)
    return path


def add_annotator(
    project_root: str | Path,
    profile: AnnotatorMetadata,
) -> AnnotatorRecord:
    """Add and select an annotator."""

    normalized = _clean_profile(profile)
    if not normalized.name:
        raise AnnotatorRegistryError("Enter the annotator’s name.")
    registry = load_annotator_registry(project_root)
    record = AnnotatorRecord(**normalized.model_dump())
    registry.annotators.append(record)
    registry.active_annotator_id = record.annotator_id
    save_annotator_registry(project_root, registry)
    return record


def update_annotator(
    project_root: str | Path,
    annotator_id: str,
    profile: AnnotatorMetadata,
) -> AnnotatorRecord:
    """Replace editable fields while retaining the stable identifier."""

    normalized = _clean_profile(profile)
    if not normalized.name:
        raise AnnotatorRegistryError("Enter the annotator’s name.")
    registry = load_annotator_registry(project_root)
    for index, existing in enumerate(registry.annotators):
        if existing.annotator_id == annotator_id:
            record = AnnotatorRecord(
                annotator_id=annotator_id,
                **normalized.model_dump(),
            )
            registry.annotators[index] = record
            save_annotator_registry(project_root, registry)
            return record
    raise AnnotatorRegistryError("The selected annotator does not exist.")


def activate_annotator(project_root: str | Path, annotator_id: str) -> AnnotatorRecord:
    """Choose the annotator reused by document preparation."""

    registry = load_annotator_registry(project_root)
    record = next(
        (
            annotator
            for annotator in registry.annotators
            if annotator.annotator_id == annotator_id
        ),
        None,
    )
    if record is None:
        raise AnnotatorRegistryError("The selected annotator does not exist.")
    registry.active_annotator_id = annotator_id
    save_annotator_registry(project_root, registry)
    return record


def remove_annotator(project_root: str | Path, annotator_id: str) -> AnnotatorRegistry:
    """Remove a profile from project configuration without altering review history."""

    registry = load_annotator_registry(project_root)
    retained = [
        annotator
        for annotator in registry.annotators
        if annotator.annotator_id != annotator_id
    ]
    if len(retained) == len(registry.annotators):
        raise AnnotatorRegistryError("The selected annotator does not exist.")
    registry.annotators = retained
    if registry.active_annotator_id == annotator_id:
        registry.active_annotator_id = (
            retained[0].annotator_id if retained else None
        )
    save_annotator_registry(project_root, registry)
    return registry
